name: flutter_ecomm_clone
description: 'A new Flutter project.'
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter
  get_it: ^7.7.0
  go_router: ^11.1.4
  application:
    path: packages/domain
  data:
    path: packages/data
  ui:
    path: packages/ui

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
