name: flutter_ecomm_clone
description: 'A new Flutter project.'
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  go_router: ^11.1.4
  data:
    path: packages/data
  domain:
    path: packages/domain
  l10n:
    path: packages/l10n
  ui:
    path: packages/ui

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
