name: l10n
description: A new Flutter package project.
version: 0.0.1

environment:
  sdk: '>=3.3.4 <4.0.0'
  flutter: '>=3.19.6'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
